/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// ADOBE_materials_clearcoat_tint — Complete
//   Material                 material.ADOBE_materials_clearcoat_tint.schema.json
import type { GlTFProperty, TextureInfo } from "../specification.js";

/**
 * glTF extension that defines the colour tint of the clearcoat.
 */
export type Material = GlTFProperty & {
  /**
   * The transmittance of the clearcoat layer.
   *
   * @minItems 3
   * @maxItems 3
   */
  clearcoatTintFactor?: [number, number, number];
  /**
   * The clearcoat layer tint texture.
   */
  clearcoatTintTexture?: TextureInfo;
};
