/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// AGI_stk_metadata — Complete
//   GlTF                     gltf.AGI_stk_metadata.schema.json
//   Node                     node.AGI_stk_metadata.schema.json
//   SolarPanelGroup          solarPanelGroup.schema.json
import type { GlTFProperty } from "../specification.js";

/** GlTF Extension that defines metadata for use with STK (Systems Tool Kit). */
export type GlTF = GlTFProperty & {
  /**
   * An array of solar panel groups.
   *
   * @minItems 1
   */
  solarPanelGroups?: SolarPanelGroup[];
};

/** A solar panel group definition. */
export type SolarPanelGroup = GlTFProperty & {
  /**
   * The name of this solar panel group. The group name must be unique within
   * this model, and may not contain spaces.
   */
  name: string;
  /**
   * The percentage, from 0.0 to 100.0, of how efficiently the solar cells
   * convert solar to electrical energy.
   */
  efficiency: number;
};

/**
 * GlTF Extension for an individual node in a glTF model, to associate it with
 * the model's root AGI_stk_metadata object.
 */
export type Node = GlTFProperty & {
  /** The name of a Solar Panel Group that includes this node. */
  solarPanelGroupName?: string;
  /**
   * Set to true to indicate that this node's geometry does not obscure any
   * sensors' view in the STK Sensor Obscuration tool.
   */
  noObscuration?: boolean;
};
