/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// AGI_articulations — Complete
//   Articulation             articulation.schema.json
//   ArticulationStage        articulation.stage.schema.json
//   GlTF                     gltf.AGI_articulations.schema.json
//   Node                     node.AGI_articulations.schema.json
import type { GlTFProperty } from "../specification.js";

/**
 * A model articulation definition.
 */
export type Articulation = GlTFProperty & {
  /**
   * The name of this articulation.  The articulation name must be unique within this model.  Articulation names may not contain spaces.
   */
  name: string;
  /**
   * An array of stages, each of which defines a degree of freedom of movement.
   *
   * @minItems 1
   */
  stages: ArticulationStage[];
  /**
   * The local forward vector for the associated node, for the purpose of pointing at a target or other object.
   *
   * @minItems 3
   * @maxItems 3
   */
  pointingVector?: [number, number, number];
};

/**
 * One stage of a model articulation definition.
 */
export type ArticulationStage = GlTFProperty & {
  /**
   * The name of this articulation stage.  The articulation stage name must be unique only within the containing articulation.  Articulation Stage names may not contain spaces.
   */
  name: string;
  /**
   * The type of motion applied by this articulation stage.
   */
  type:
    | "xTranslate"
    | "yTranslate"
    | "zTranslate"
    | "xRotate"
    | "yRotate"
    | "zRotate"
    | "xScale"
    | "yScale"
    | "zScale"
    | "uniformScale"
    | string;
  /**
   * The minimum value for the range of motion of this articulation stage.
   */
  minimumValue: number;
  /**
   * The maximum value for the range of motion of this articulation stage.
   */
  maximumValue: number;
  /**
   * The initial value for this articulation stage.
   */
  initialValue: number;
};

/**
 * glTF Extension that defines metadata for applying external analysis or effects to a model.
 */
export type GlTF = GlTFProperty & {
  /**
   * An array of articulations.
   *
   * @minItems 1
   */
  articulations?: Articulation[];
};

/**
 * glTF Extension for an individual node in a glTF model, to associate it with the model's root AGI_articulations object.
 */
export type Node = GlTFProperty & {
  /**
   * Set to true to indicate that this node's origin and orientation act as an attach point for external objects, analysis, or effects.
   */
  isAttachPoint?: boolean;
  /**
   * The name of an Articulation that applies to this node.
   */
  articulationName?: string;
};
