// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// EXT_mesh_manifold — Complete
//   Mesh                     mesh.EXT_mesh_manifold.schema.json
import type { GlTFId, GlTFProperty, MeshPrimitive } from "../specification.js";

/**
 * glTF extension defines manifoldness for a mesh.
 */
export type Mesh = GlTFProperty & {
  manifoldPrimitive: MeshPrimitive;
  /**
   * The index of the accessor that contains the vertex sparse indices for merging into a manifold.
   */
  mergeIndices?: GlTFId;
  /**
   * The index of the accessor that contains the vertex sparse values for merging into a manifold.
   */
  mergeValues?: GlTFId;
};
