/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// EXT_mesh_primitive_restart — Complete
//   EXTMeshPrimitiveRestart  EXT_mesh_primitive_restart.schema.json
//   PrimitiveGroup           primitiveGroup.schema.json
import type { GlTFId, GlTFProperty } from "../specification.js";

/**
 * glTF extension enabling the use of primitive restart values in index buffers
 */
export type EXTMeshPrimitiveRestart = GlTFProperty & {
  /**
   * The list of groups of primitives that can be drawn using a single index buffer with primitive restart
   *
   * @minItems 1
   */
  primitiveGroups: PrimitiveGroup[];
};

/**
 * A group of primitives that can be drawn together using a single index buffer containing restart values
 */
export type PrimitiveGroup = GlTFProperty & {
  /**
   * The indices of the primitives that will be combined and drawn using a single set of indices
   *
   * @minItems 1
   */
  primitives: GlTFId[];
  /**
   * The index of the accessor that contains the vertex indices
   */
  indices: GlTFId;
};
