/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// EXT_lights_ies — Complete
//   GlTF                     glTF.EXT_lights_ies.schema.json
//   LightProfile             lightProfile.schema.json
//   Node                     node.EXT_lights_ies.schema.json
import type {
  GlTFChildOfRootProperty,
  GlTFId,
  GlTFProperty,
} from "../specification.js";

/** GlTF extension that enables the use of IES light profiles. */
export type GlTF = GlTFProperty & {
  /** @minItems 1 */
  lights: LightProfile[];
};

/** An IES light profile. */
export type LightProfile = GlTFChildOfRootProperty &
  (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  ) & {
    /** The URI (or IRI) of the light profile. */
    uri?: string;
    /**
     * The light profile's media type. This field **MUST** be defined when
     * `bufferView` is defined.
     */
    mimeType?: "application/x-ies-lm-63" | string;
    /**
     * The index of the bufferView that contains the IES light profile. This
     * field **MUST NOT** be defined when `uri` is defined.
     */
    bufferView?: GlTFId;
  } & (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  );

export type Node = GlTFProperty & {
  /** The id of the light profile referenced by this node. */
  light: GlTFId;
  /** Non-negative factor to scale the light's intensity. */
  multiplier?: number;
  /**
   * RGB value for the light's color in linear space.
   *
   * @minItems 3
   * @maxItems 3
   */
  color?: [number, number, number];
};
