// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// EXT_texture_webp — Complete, Ratified by the Khronos Group
//   GlTF                     glTF.EXT_texture_webp.schema.json
import type { GlTFId, GlTFProperty } from "../specification.js";

/**
 * glTF extension to specify textures using the WebP image format.
 */
export type GlTF = GlTFProperty & {
  /**
   * The index of the WebP image.
   */
  source?: GlTFId;
};
