// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// Every registry extension whose status is Complete.
export type * as KHR_animation_pointer from "./KHR_animation_pointer.js";
export type * as KHR_draco_mesh_compression from "./KHR_draco_mesh_compression.js";
export type * as KHR_gaussian_splatting from "./KHR_gaussian_splatting.js";
export type * as KHR_lights_punctual from "./KHR_lights_punctual.js";
export type * as KHR_materials_anisotropy from "./KHR_materials_anisotropy.js";
export type * as KHR_materials_clearcoat from "./KHR_materials_clearcoat.js";
export type * as KHR_materials_dispersion from "./KHR_materials_dispersion.js";
export type * as KHR_materials_emissive_strength from "./KHR_materials_emissive_strength.js";
export type * as KHR_materials_ior from "./KHR_materials_ior.js";
export type * as KHR_materials_iridescence from "./KHR_materials_iridescence.js";
export type * as KHR_materials_sheen from "./KHR_materials_sheen.js";
export type * as KHR_materials_specular from "./KHR_materials_specular.js";
export type * as KHR_materials_transmission from "./KHR_materials_transmission.js";
export type * as KHR_materials_unlit from "./KHR_materials_unlit.js";
export type * as KHR_materials_variants from "./KHR_materials_variants.js";
export type * as KHR_materials_volume from "./KHR_materials_volume.js";
export type * as KHR_node_hoverability from "./KHR_node_hoverability.js";
export type * as KHR_node_selectability from "./KHR_node_selectability.js";
export type * as KHR_node_visibility from "./KHR_node_visibility.js";
export type * as KHR_texture_basisu from "./KHR_texture_basisu.js";
export type * as KHR_texture_transform from "./KHR_texture_transform.js";
export type * as KHR_xmp_json_ld from "./KHR_xmp_json_ld.js";
export type * as ADOBE_materials_clearcoat_tint from "./ADOBE_materials_clearcoat_tint.js";
export type * as AGI_articulations from "./AGI_articulations.js";
export type * as AGI_stk_metadata from "./AGI_stk_metadata.js";
export type * as EXT_lights_ies from "./EXT_lights_ies.js";
export type * as EXT_mesh_gpu_instancing from "./EXT_mesh_gpu_instancing.js";
export type * as EXT_mesh_manifold from "./EXT_mesh_manifold.js";
export type * as EXT_mesh_primitive_restart from "./EXT_mesh_primitive_restart.js";
export type * as EXT_meshopt_compression from "./EXT_meshopt_compression.js";
export type * as EXT_texture_webp from "./EXT_texture_webp.js";
export type * as MSFT_lod from "./MSFT_lod.js";
export type * as MSFT_packing_normalRoughnessMetallic from "./MSFT_packing_normalRoughnessMetallic.js";
export type * as MSFT_packing_occlusionRoughnessMetallic from "./MSFT_packing_occlusionRoughnessMetallic.js";
export type * as NV_materials_mdl from "./NV_materials_mdl.js";
