// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_anisotropy — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_anisotropy.schema.json
import type { GlTFProperty, TextureInfo } from "../specification.js";

/**
 * glTF extension that defines anisotropy.
 */
export type Material = GlTFProperty & {
  /**
   * The anisotropy strength.
   */
  anisotropyStrength?: number;
  /**
   * The rotation of the anisotropy.
   */
  anisotropyRotation?: number;
  /**
   * The anisotropy texture.
   */
  anisotropyTexture?: TextureInfo;
};
