/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_sheen — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_sheen.schema.json
import type { GlTFProperty, TextureInfo } from "../specification.js";

/** GlTF extension that defines the sheen material model. */
export type Material = GlTFProperty & {
  /**
   * Color of the sheen layer (in linear space).
   *
   * @minItems 3
   * @maxItems 3
   */
  sheenColorFactor?: [number, number, number];
  /** The sheen color (RGB) texture. */
  sheenColorTexture?: TextureInfo;
  /** The sheen layer roughness. */
  sheenRoughnessFactor?: number;
  /** The sheen roughness (Alpha) texture. */
  sheenRoughnessTexture?: TextureInfo;
};
