/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_variants — Complete, Ratified by the Khronos Group
//   GlTF                     glTF.KHR_materials_variants.schema.json
//   MeshPrimitive            mesh.primitive.KHR_materials_variants.schema.json
import type {
  GlTFChildOfRootProperty,
  GlTFId,
  GlTFProperty,
} from "../specification.js";

/** GlTF extension that defines a material variations for mesh primitives */
export type GlTF = GlTFProperty & {
  /**
   * @minItems 1
   *
   * Items: An object defining a valid material variant
   */
  variants: [
    GlTFChildOfRootProperty & {
      /** The name of the material variant */
      name: string;
    } & {
      /** The name of the material variant */
      name: string;
    },
    ...(GlTFChildOfRootProperty & {
      /** The name of the material variant */
      name: string;
    } & {
      /** The name of the material variant */
      name: string;
    })[],
  ];
};

export type MeshPrimitive = GlTFProperty & {
  /**
   * A list of material to variant mappings
   *
   * @minItems 1
   */
  mappings: [
    GlTFProperty & {
      /**
       * An array of variant index values.
       *
       * @minItems 1
       */
      variants: GlTFId[];
      /** The material associated with the set of variants. */
      material: GlTFId;
      /** The user-defined name of this variant material mapping. */
      name?: string;
    } & {
      /**
       * An array of variant index values.
       *
       * @minItems 1
       */
      variants: GlTFId[];
      /** The material associated with the set of variants. */
      material: GlTFId;
      /** The user-defined name of this variant material mapping. */
      name?: string;
    },
    ...(GlTFProperty & {
      /**
       * An array of variant index values.
       *
       * @minItems 1
       */
      variants: GlTFId[];
      /** The material associated with the set of variants. */
      material: GlTFId;
      /** The user-defined name of this variant material mapping. */
      name?: string;
    } & {
      /**
       * An array of variant index values.
       *
       * @minItems 1
       */
      variants: GlTFId[];
      /** The material associated with the set of variants. */
      material: GlTFId;
      /** The user-defined name of this variant material mapping. */
      name?: string;
    })[],
  ];
};
