/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_volume — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_volume.schema.json
import type { GlTFProperty, TextureInfo } from "../specification.js";

/**
 * glTF extension that defines the parameters for the volume of a material.
 */
export type Material = GlTFProperty & {
  /**
   * Thickness of the volume.
   */
  thicknessFactor?: number;
  /**
   * Texture that defines the thickness of the volume, stored in the G channel.
   */
  thicknessTexture?: TextureInfo;
  /**
   * Average distance that light travels in the medium before interacting with a particle.
   */
  attenuationDistance?: number;
  /**
   * Color that white light turns into due to absorption when reaching the attenuation distance.
   *
   * @minItems 3
   * @maxItems 3
   */
  attenuationColor?: [number, number, number];
};
