// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_node_hoverability — Complete, Ratified by the Khronos Group
//   Node                     node.KHR_node_hoverability.schema.json
import type { GlTFProperty } from "../specification.js";

/** GlTF extension that defines node's hoverability. */
export type Node = GlTFProperty & {
  /** Specifies whether the node is hoverable. */
  hoverable?: boolean;
};
