// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_ior — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_ior.schema.json
import type { GlTFProperty } from "../specification.js";

/**
 * glTF extension that defines the index of refraction of a material.
 */
export type Material = GlTFProperty & {
  /**
   * The index of refraction.
   */
  ior?: number;
};
