/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_lights_punctual — Complete, Ratified by the Khronos Group
//   GlTF                     glTF.KHR_lights_punctual.schema.json
//   Light                    light.schema.json
//   LightSpot                light.spot.schema.json
//   Node                     node.KHR_lights_punctual.schema.json
import type {
  GlTFChildOfRootProperty,
  GlTFId,
  GlTFProperty,
} from "../specification.js";

export type GlTF = GlTFProperty & {
  /** @minItems 1 */
  lights: Light[];
};

/** A directional, point, or spot light. */
export type Light = GlTFChildOfRootProperty & {
  /**
   * Color of the light source.
   *
   * @minItems 3
   * @maxItems 3
   */
  color?: [number, number, number];
  /**
   * Intensity of the light source. `point` and `spot` lights use luminous
   * intensity in candela (lm/sr) while `directional` lights use illuminance in
   * lux (lm/m^2)
   */
  intensity?: number;
  spot?: LightSpot;
  /** Specifies the light type. */
  type: "directional" | "point" | "spot";
  /**
   * A distance cutoff at which the light's intensity may be considered to have
   * reached zero.
   */
  range?: number;
};

export type LightSpot = GlTFProperty & {
  /** Angle in radians from centre of spotlight where falloff begins. */
  innerConeAngle?: number;
  /** Angle in radians from centre of spotlight where falloff ends. */
  outerConeAngle?: number;
};

export type Node = GlTFProperty & {
  /** The id of the light referenced by this node. */
  light: GlTFId;
};
