// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_clearcoat — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_clearcoat.schema.json
import type {
  GlTFProperty,
  MaterialNormalTextureInfo,
  TextureInfo,
} from "../specification.js";

/** GlTF extension that defines the clearcoat material layer. */
export type Material = GlTFProperty & {
  /** The clearcoat layer intensity. */
  clearcoatFactor?: number;
  /** The clearcoat layer intensity texture. */
  clearcoatTexture?: TextureInfo;
  /** The clearcoat layer roughness. */
  clearcoatRoughnessFactor?: number;
  /** The clearcoat layer roughness texture. */
  clearcoatRoughnessTexture?: TextureInfo;
  /** The clearcoat normal map texture. */
  clearcoatNormalTexture?: MaterialNormalTextureInfo;
};
