/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_specular — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_specular.schema.json
import type { GlTFProperty, TextureInfo } from "../specification.js";

/** GlTF extension that defines the strength of the specular reflection. */
export type Material = GlTFProperty & {
  /** The strength of the specular reflection. */
  specularFactor?: number;
  /** A texture that defines the specular factor in the alpha channel. */
  specularTexture?: TextureInfo;
  /**
   * The F0 RGB color of the specular reflection.
   *
   * @minItems 3
   * @maxItems 3
   */
  specularColorFactor?: [number, number, number];
  /** A texture that defines the F0 color of the specular reflection. */
  specularColorTexture?: TextureInfo;
};
