// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_texture_basisu — Complete, Ratified by the Khronos Group
//   Texture                  texture.KHR_texture_basisu.schema.json
import type { GlTFId, GlTFProperty } from "../specification.js";

/**
 * glTF extension to specify textures using the KTX v2 images with Basis Universal supercompression.
 */
export type Texture = GlTFProperty & {
  /**
   * The index of the image which points to a KTX v2 resource with Basis Universal supercompression.
   */
  source?: GlTFId;
};
