// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_transmission — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_transmission.schema.json
import type { GlTFProperty, TextureInfo } from "../specification.js";

/**
 * glTF extension that defines the optical transmission of a material.
 */
export type Material = GlTFProperty & {
  /**
   * The base percentage of light transmitted through the surface.
   */
  transmissionFactor?: number;
  /**
   * A texture that defines the transmission percentage of the surface, sampled from the R channel. These values are linear, and will be multiplied by transmissionFactor.
   */
  transmissionTexture?: TextureInfo;
};
