// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_draco_mesh_compression — Complete, Ratified by the Khronos Group
//   MeshPrimitive            mesh.primitive.KHR_draco_mesh_compression.schema.json
import type { GlTFId, GlTFProperty } from "../specification.js";

export type MeshPrimitive = GlTFProperty & {
  /** The index of the bufferView. */
  bufferView: GlTFId;
  /**
   * A dictionary object, where each key corresponds to an attribute and its
   * unique attribute id stored in the compressed geometry.
   */
  attributes: {
    [k: string]: GlTFId;
  };
};
