// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_iridescence — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_iridescence.schema.json
import type { GlTFProperty, TextureInfo } from "../specification.js";

/** GlTF extension that defines an iridescence effect. */
export type Material = GlTFProperty & {
  /** The iridescence intensity factor. */
  iridescenceFactor?: number;
  /** The iridescence intensity texture. */
  iridescenceTexture?: TextureInfo;
  /** The index of refraction of the dielectric thin-film layer. */
  iridescenceIor?: number;
  /** The minimum thickness of the thin-film layer given in nanometers. */
  iridescenceThicknessMinimum?: number;
  /** The maximum thickness of the thin-film layer given in nanometers. */
  iridescenceThicknessMaximum?: number;
  /** The thickness texture of the thin-film layer. */
  iridescenceThicknessTexture?: TextureInfo;
};
