// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_dispersion — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_dispersion.schema.json
import type { GlTFProperty } from "../specification.js";

/** GlTF extension that defines the strength of dispersion. */
export type Material = GlTFProperty & {
  /**
   * This parameter defines dispersion in terms of the 20/Abbe number
   * formulation.
   */
  dispersion?: number;
};
