/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_texture_transform — Complete, Ratified by the Khronos Group
//   TextureInfo              textureInfo.KHR_texture_transform.schema.json
import type { GlTFProperty } from "../specification.js";

/**
 * GlTF extension that enables shifting and scaling UV coordinates on a
 * per-texture basis
 */
export type TextureInfo = GlTFProperty & {
  /**
   * The offset of the UV coordinate origin as a factor of the texture
   * dimensions.
   *
   * @minItems 2
   * @maxItems 2
   */
  offset?: [number, number];
  /** Rotate the UVs by this many radians counter-clockwise around the origin. */
  rotation?: number;
  /**
   * The scale factor applied to the components of the UV coordinates.
   *
   * @minItems 2
   * @maxItems 2
   */
  scale?: [number, number];
  /**
   * Overrides the textureInfo texCoord value if supplied, and if this extension
   * is supported.
   */
  texCoord?: number;
};
