// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_emissive_strength — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_emissive_strength.schema.json
import type { GlTFProperty } from "../specification.js";

/** GlTF extension that adjusts the strength of emissive material properties. */
export type Material = GlTFProperty & {
  /**
   * The strength adjustment to be multiplied with the material's emissive
   * value.
   */
  emissiveStrength?: number;
};
