// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_materials_unlit — Complete, Ratified by the Khronos Group
//   Material                 material.KHR_materials_unlit.schema.json
import type { GlTFProperty } from "../specification.js";

/**
 * glTF extension that defines the unlit material model.
 */
export type Material = GlTFProperty & {};
