// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// KHR_animation_pointer — Complete, Ratified by the Khronos Group
//   AnimationChannelTarget   animation.channel.target.KHR_animation_pointer.schema.json
import type { GlTFProperty } from "../specification.js";

/** Extension object providing the JSON Pointer to the animated property. */
export type AnimationChannelTarget = GlTFProperty & {
  /**
   * JSON pointer to the animated property. The animation channel path value
   * **MUST** be `pointer`.
   */
  pointer: string;
};
