// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// MSFT_packing_occlusionRoughnessMetallic — Complete
//   GlTF                     glTF.MSFT_packing_occlusionRoughnessMetallic.schema.json
import type { GlTFId, GlTFProperty } from "../specification.js";

/**
 * glTF extension the specifies a packing of occlusion, roughness and metallic in a single texture and a two channel normal map.
 */
export type GlTF = GlTFProperty & {
  /**
   * A texture with packing Occlusion (R), Roughness (G), Metallic (B).
   */
  occlusionRoughnessMetallicTexture?: {
    /**
     * The index of the texture.
     */
    index?: GlTFId;
  };
  /**
   * A texture with packing Roughness (R), Metallic (G), Occlusion (B).
   */
  roughnessMetallicOcclusionTexture?: {
    /**
     * The index of the texture.
     */
    index?: GlTFId;
  };
  /**
   * A texture which contains two channel (RG) normal map.
   */
  normalTexture?: {
    /**
     * The index of the texture.
     */
    index?: GlTFId;
  };
};
