/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// MSFT_lod — Complete
//   GlTF                     glTF.MSFT_lod.schema.json
import type { GlTFProperty } from "../specification.js";

/** GlTF extension for specifying levels of detail (LOD). */
export type GlTF = GlTFProperty & {
  /**
   * Array containing the indices of progressively lower LOD nodes.
   *
   * @minItems 1
   */
  ids?: number[];
};
