// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// MSFT_packing_normalRoughnessMetallic — Complete
//   GlTF                     glTF.MSFT_packing_normalRoughnessMetallic.schema.json
import type { GlTFId, GlTFProperty } from "../specification.js";

/**
 * GlTF extension the specifies a packing of normal, roughness and metallic in a
 * single texture.
 */
export type GlTF = GlTFProperty & {
  /** A texture with the packing Normal (RG), Roughness (B), Metallic (A). */
  normalRoughnessMetallicTexture?: {
    /** The index of the texture. */
    index?: GlTFId;
  };
};
