/* eslint-disable jsdoc/check-tag-names */
// Generated by scripts/generate.js from KhronosGroup/glTF@c184327.
// Run that script to update; do not edit by hand.
// NV_materials_mdl — Complete
//   BsdfMeasurement          bsdfMeasurement.schema.json
//   FunctionCallArgument     functionCall.argument.schema.json
//   FunctionCall             functionCall.schema.json
//   FunctionCallType         functionCall.type.schema.json
//   GlTF                     glTF.NV_materials_mdl.schema.json
//   Material                 material.NV_materials_mdl.schema.json
//   Module                   module.schema.json
import type {
  GlTFChildOfRootProperty,
  GlTFId,
  GlTFProperty,
} from "../specification.js";

/**
 * A BSDF measurement (MBSDF) as defined in the MDL Language Specification.
 */
export type BsdfMeasurement = GlTFChildOfRootProperty & {
  /**
   * The URI (or IRI) of the MBSDF.
   */
  uri?: string;
  /**
   * The ID of the bufferView containing the MBSDF.  This field **MUST NOT** be defined if `uri` is defined.
   */
  bufferView?: GlTFId;
  /**
   * The BSDF measurement's media type.  This field **MUST** be defined when `bufferView` is defined.
   */
  mimeType?: "application/vnd.mdl-mbsdf" | string;
} & {
  [k: string]: unknown;
};

/**
 * Named function call argument. Can be another function call or a constant value.
 */
export type FunctionCallArgument = GlTFProperty & {
  /**
   * The name of the named argument.
   */
  name?: string;
  /**
   * The type of the value argument.  This field **MUST** be defined if `value` is defined and **MUST NOT** be defined if `functionCall` is defined.
   */
  type?: FunctionCallType;
  /**
   * The ID of a function call.  This field **MUST NOT** be defined if `value` is defined.
   */
  functionCall?: GlTFId;
  /**
   * The literal value of the value argument.  This field **MUST NOT** be defined if `functionCall` is defined.
   */
  value?:
    | boolean
    | number
    | string
    | [boolean | number | number, boolean | number | number]
    | [
        boolean | number | number,
        boolean | number | number,
        boolean | number | number,
      ]
    | [
        boolean | number | number,
        boolean | number | number,
        boolean | number | number,
        boolean | number | number,
      ]
    | [number, number, number, number]
    | [number, number, number, number, number]
    | [number, number, number, number, number, number]
    | [number, number, number, number, number, number, number]
    | [number, number, number, number, number, number, number, number]
    | [number, number, number, number, number, number, number, number, number]
    | [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
      ]
    | [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
      ]
    | [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
      ]
    | [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
      ]
    | [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
      ]
    | [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
      ]
    | [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
      ]
    | (
        | boolean
        | number
        | string
        | [boolean | number | number, boolean | number | number]
        | [
            boolean | number | number,
            boolean | number | number,
            boolean | number | number,
          ]
        | [
            boolean | number | number,
            boolean | number | number,
            boolean | number | number,
            boolean | number | number,
          ]
        | [number, number, number, number]
        | [number, number, number, number, number]
        | [number, number, number, number, number, number]
        | [number, number, number, number, number, number, number]
        | [number, number, number, number, number, number, number, number]
        | [
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
          ]
        | [
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
          ]
        | [
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
          ]
        | [
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
          ]
        | [
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
          ]
        | [
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
          ]
        | [
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
          ]
        | [
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
            number,
          ]
      )[];
} & {
  [k: string]: unknown;
};

/**
 * MDL type describing either a built-in or user-defined type, or an array of a built-in or user-defined type.
 */
export type FunctionCallType = GlTFProperty & {
  /**
   * The ID of the containing module.  This field **MUST NOT** be defined if a built-in type is specified.
   */
  module?: GlTFId;
  /**
   * The unqualified name of the type.
   */
  typeName: string;
  /**
   * The array size. If this field is defined the type is considered to be a array.
   */
  arraySize?: number;
  /**
   * The name of the type modifier.
   */
  modifier?: "varying" | "uniform";
};

/**
 * Function call with its list of arguments. Can represent the entry point into a function call graph or be a node in such a graph.
 */
export type FunctionCall = GlTFChildOfRootProperty & {
  /**
   * The ID of the containing module.  This field **MUST NOT** be defined if a built-in function is specified.
   */
  module?: GlTFId;
  /**
   * The unqualified name of the function.
   */
  functionName: string;
  /**
   * The return type of the function.
   */
  type: FunctionCallType;
  /**
   * A list of named value and/or function call arguments.  Multiple arguments with the same name **MUST NOT** exist.
   *
   * @minItems 1
   */
  arguments?: FunctionCallArgument[];
};

/**
 * glTF extension that enables using MDL materials.
 */
export type GlTF = GlTFProperty & {
  /**
   * The list of all MDL modules.
   *
   * @minItems 1
   */
  modules?: Module[];
  /**
   * The list of all function calls.
   *
   * @minItems 1
   */
  functionCalls?: FunctionCall[];
  /**
   * The list of all BSDF measurements.
   *
   * @minItems 1
   */
  bsdfMeasurements?: BsdfMeasurement[];
};

/**
 * An MDL module.
 */
export type Module = GlTFChildOfRootProperty & {
  /**
   * The URI (or IRI) of the MDL module.
   */
  uri?: string;
  /**
   * The ID of the bufferView containing the MDL module.  This field **MUST NOT** be defined if `uri` is defined.
   */
  bufferView?: GlTFId;
  /**
   * The MDL module's media type.  This field **MUST** be defined when `bufferView` is defined.
   */
  mimeType?: "application/vnd.mdl" | string;
  /**
   * Relative path of the module.  This field **MUST** be defined if `bufferView` is defined or `uri` is defined and contains a data-URI, otherwise this field **MUST NOT** be defined.
   */
  modulePath?: string;
} & (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  ) & {
    /**
     * The URI (or IRI) of the MDL module.
     */
    uri?: string;
    /**
     * The ID of the bufferView containing the MDL module.  This field **MUST NOT** be defined if `uri` is defined.
     */
    bufferView?: GlTFId;
    /**
     * The MDL module's media type.  This field **MUST** be defined when `bufferView` is defined.
     */
    mimeType?: "application/vnd.mdl" | string;
    /**
     * Relative path of the module.  This field **MUST** be defined if `bufferView` is defined or `uri` is defined and contains a data-URI, otherwise this field **MUST NOT** be defined.
     */
    modulePath?: string;
  };

/**
 * glTF extension that enables using MDL materials.
 */
export type Material = GlTFProperty & {
  /**
   * The index of the MDL function call. The reference function call **MUST** represent the entry point to a function call graph and have the return type `material`.
   */
  functionCall: GlTFId;
};
